### ISSUE TITLE
Sitecore.Support.137593 artefacts

### ISSUE THREAD

**Issue by AgnieszkaS** [SitecoreSupport/Sitecore.Support.137593#1]
Hi,

Where can I find the dll for this issue? On the both branches I can see only the readme file and license.

Kind regards,   
Agnieszka

**Comment by RomanChernyk** [comment]
Hi,

It looks like this repo has been created by mistake.

Please use access the following one instead:
https://github.com/SitecoreSupport/Sitecore.Support.138194/releases

**Comment by AgnieszkaS** [comment]
Thanks!
